//! Stage 0 — Inventory.
//!
//! Job    Enumerate candidate source files and classify what to exclude.
//! In     Repository root path
//! Out    Inventory { files, excluded }
//! Fails  Unreadable path -> skipped and counted, never fatal.

use crate::types::{FileClass, FileRecord, Language};
use anyhow::{Context, Result};
use ignore::WalkBuilder;
use std::path::{Path, PathBuf};

/// Directories never worth walking. Most are gitignored already; this catches
/// repositories where they are not.
const VENDOR_DIRS: &[&str] = &[
    "node_modules",
    "bower_components",
    "vendor",
    "dist",
    "build",
    "out",
    "coverage",
    "target",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".output",
    "storybook-static",
    "__snapshots__",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    ".tox",
    "site-packages",
];

/// Markers that appear in the head of machine-written files.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "This file was automatically generated",
    // Django migration snapshots. Coupled to models, but auto-written and
    // numerous; mapping them adds files without architecture.
    "Generated by Django",
];

/// Files above this size are bundles or data, not code worth mapping.
const MAX_SOURCE_BYTES: u64 = 512 * 1024;

/// A line this long means minified output regardless of what else it contains.
const MINIFIED_LINE_BYTES: usize = 2_000;

#[derive(Debug, Default, Clone)]
pub struct ExcludeStats {
    pub generated: usize,
    pub config: usize,
    pub declarations: usize,
    pub too_large: usize,
    pub unreadable: usize,
    /// Files in no supported language. Named `non_js_ts` before M4 added
    /// Python; renamed rather than left lying.
    pub non_supported: usize,
}

pub struct Inventory {
    pub root: PathBuf,
    /// Analyzed files only (source + test), densely indexed by `FileId`.
    pub files: Vec<FileRecord>,
    /// Everything recognized but deliberately not analyzed.
    pub skipped: Vec<FileRecord>,
    pub excluded: ExcludeStats,
}

impl Inventory {
    pub fn get(&self, id: usize) -> &FileRecord {
        &self.files[id]
    }

    pub fn len(&self) -> usize {
        self.files.len()
    }

    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }

    pub fn total_loc(&self) -> usize {
        self.files.iter().map(|f| f.loc).sum()
    }
}

pub fn collect(root: &Path) -> Result<Inventory> {
    let root = root
        .canonicalize()
        .with_context(|| format!("cannot open repository root {}", root.display()))?;
    // Windows canonicalization yields a \\?\ extended-length prefix, which is
    // correct but unreadable in output. Strip it for display purposes.
    let root = strip_unc_prefix(root);

    let mut stats = ExcludeStats::default();
    let mut analyzed: Vec<FileRecord> = Vec::new();
    let mut skipped: Vec<FileRecord> = Vec::new();

    let walker = WalkBuilder::new(&root)
        .hidden(true)
        .git_ignore(true)
        .git_global(false)
        .parents(false)
        .filter_entry(|e| {
            let name = e.file_name().to_string_lossy();
            !VENDOR_DIRS.contains(&name.as_ref())
        })
        .build();

    for entry in walker {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => {
                stats.unreadable += 1;
                continue;
            }
        };

        if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }

        let abs = entry.path().to_path_buf();
        let Some(language) = Language::from_path(&abs) else {
            stats.non_supported += 1;
            continue;
        };

        let rel = match abs.strip_prefix(&root) {
            Ok(r) => r.to_string_lossy().replace('\\', "/"),
            Err(_) => continue,
        };

        let meta = match entry.metadata() {
            Ok(m) => m,
            Err(_) => {
                stats.unreadable += 1;
                continue;
            }
        };
        let bytes = meta.len();

        if bytes > MAX_SOURCE_BYTES {
            stats.too_large += 1;
            continue;
        }

        let text = match std::fs::read_to_string(&abs) {
            Ok(t) => t,
            Err(_) => {
                stats.unreadable += 1;
                continue;
            }
        };

        let loc = text.lines().count();
        let class = classify(&rel, &text);

        match class {
            FileClass::Generated => stats.generated += 1,
            FileClass::Config => stats.config += 1,
            FileClass::Vendored => stats.declarations += 1,
            _ => {}
        }

        let record = FileRecord {
            id: 0, // assigned below
            rel,
            abs,
            language,
            bytes,
            loc,
            class,
        };

        if class.is_analyzed() {
            analyzed.push(record);
        } else {
            skipped.push(record);
        }
    }

    // Stable ordering makes the whole pipeline reproducible run to run.
    analyzed.sort_by(|a, b| a.rel.cmp(&b.rel));
    skipped.sort_by(|a, b| a.rel.cmp(&b.rel));
    for (i, f) in analyzed.iter_mut().enumerate() {
        f.id = i;
    }

    Ok(Inventory {
        root,
        files: analyzed,
        skipped,
        excluded: stats,
    })
}

fn strip_unc_prefix(p: PathBuf) -> PathBuf {
    let s = p.to_string_lossy();
    match s.strip_prefix(r"\\?\") {
        Some(rest) => PathBuf::from(rest),
        None => p,
    }
}

fn classify(rel: &str, text: &str) -> FileClass {
    if rel.ends_with(".d.ts") {
        // Declaration files describe an API surface that already exists in the
        // implementation files; mapping both doubles the noise.
        return FileClass::Vendored;
    }
    if is_generated(text) {
        return FileClass::Generated;
    }
    if is_test(rel) {
        return FileClass::Test;
    }
    if is_config(rel) {
        return FileClass::Config;
    }
    FileClass::Source
}

fn is_test(rel: &str) -> bool {
    let lower = rel.to_ascii_lowercase();
    let base = rel.rsplit('/').next().unwrap_or(rel);
    let base_lower = base.to_ascii_lowercase();
    lower.contains("__tests__/")
        || lower.contains("__mocks__/")
        || lower.starts_with("test/")
        || lower.starts_with("tests/")
        || lower.contains("/test/")
        || lower.contains("/tests/")
        || lower.contains("/e2e/")
        || lower.contains(".test.")
        || lower.contains(".spec.")
        // Python conventions: no `.test.` infix, tests live in names.
        || base_lower.starts_with("test_")
        || base_lower.ends_with("_test.py")
        || base_lower == "conftest.py"
}

fn is_config(rel: &str) -> bool {
    let base = rel.rsplit('/').next().unwrap_or(rel);
    let lower = base.to_ascii_lowercase();
    lower.contains(".config.")
        || lower.starts_with(".eslintrc")
        || lower.starts_with(".prettierrc")
        || lower == "next-env.d.ts"
        || lower == "commitlint.config.js"
}

fn is_generated(text: &str) -> bool {
    let head: String = text.chars().take(4096).collect();
    if GENERATED_MARKERS.iter().any(|m| head.contains(m)) {
        return true;
    }
    // Minification check: a single enormous line is conclusive on its own.
    text.lines().take(200).any(|l| l.len() > MINIFIED_LINE_BYTES)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognizes_test_paths() {
        assert!(is_test("src/auth/login.test.ts"));
        assert!(is_test("src/__tests__/login.ts"));
        assert!(is_test("tests/integration/api.ts"));
        assert!(!is_test("src/auth/login.ts"));
        // "latest" contains "test" but is not a test path.
        assert!(!is_test("src/latest/index.ts"));
    }

    #[test]
    fn recognizes_config_paths() {
        assert!(is_config("next.config.js"));
        assert!(is_config("vite.config.ts"));
        assert!(!is_config("src/config/database.ts"));
    }

    #[test]
    fn detects_generated_headers_and_minification() {
        assert!(is_generated("// @generated by protoc\nexport const A = 1;"));
        assert!(is_generated(&format!("const a=1;{}\n", "x".repeat(3000))));
        assert!(!is_generated("export function real() { return 1; }"));
    }

    #[test]
    fn declaration_files_are_not_analyzed() {
        assert_eq!(classify("src/types.d.ts", "export {}"), FileClass::Vendored);
        assert!(!FileClass::Vendored.is_analyzed());
    }

    #[test]
    fn python_test_names_are_test_classed() {
        assert!(is_test("tests/test_models.py"));
        assert!(is_test("src/test_views.py"));
        assert!(is_test("pkg/auth_test.py"));
        assert!(is_test("pkg/conftest.py"));
        assert!(!is_test("pkg/models.py"));
        assert!(!is_test("pkg/latest.py"));
    }

    #[test]
    fn django_migrations_are_generated() {
        assert!(is_generated("# Generated by Django 5.0 on 2024-01-01\n"));
        assert_eq!(
            classify("app/migrations/0001_initial.py", "# Generated by Django 5.0\n"),
            FileClass::Generated
        );
    }

    #[test]
    fn python_extension_maps_to_python() {
        assert_eq!(
            Language::from_path(std::path::Path::new("pkg/models.py")),
            Some(Language::Python)
        );
        assert_eq!(Language::Python.name(), "Python");
    }
}
