//! Stage 0 — Inventory.
//!
//! Job    Enumerate candidate source files and classify what to exclude.
//! In     Repository root path
//! Out    Inventory { files, excluded }
//! Fails  Unreadable path -> skipped and counted, never fatal.

use crate::cache::{StoredFile, sha_hex};
use crate::types::{FileClass, FileRecord, Language};
use anyhow::{Context, Result};
use ignore::WalkBuilder;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Directories never worth walking. Most are gitignored already; this catches
/// repositories where they are not.
const VENDOR_DIRS: &[&str] = &[
    "node_modules",
    "bower_components",
    "vendor",
    "dist",
    "build",
    "out",
    "coverage",
    "target",
    ".next",
    ".nuxt",
    ".svelte-kit",
    ".turbo",
    ".output",
    "storybook-static",
    "__snapshots__",
    "__pycache__",
    ".venv",
    "venv",
    "env",
    ".tox",
    "site-packages",
];

/// Markers that appear in the head of machine-written files.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "do not edit",
    "auto-generated",
    "autogenerated",
    "This file was automatically generated",
    // Django migration snapshots. Coupled to models, but auto-written and
    // numerous; mapping them adds files without architecture.
    "Generated by Django",
];

/// Files above this size are bundles or data, not code worth mapping.
const MAX_SOURCE_BYTES: u64 = 512 * 1024;

/// A line this long means minified output regardless of what else it contains.
const MINIFIED_LINE_BYTES: usize = 2_000;

#[derive(Debug, Default, Clone)]
pub struct ExcludeStats {
    pub generated: usize,
    pub config: usize,
    pub declarations: usize,
    pub too_large: usize,
    pub unreadable: usize,
    /// Files in no supported language. Named `non_js_ts` before M4 added
    /// Python; renamed rather than left lying.
    pub non_supported: usize,
}

pub struct Inventory {
    pub root: PathBuf,
    /// Analyzed files only (source + test), densely indexed by `FileId`.
    pub files: Vec<FileRecord>,
    /// Everything recognized but deliberately not analyzed.
    pub skipped: Vec<FileRecord>,
    pub excluded: ExcludeStats,
}

impl Inventory {
    pub fn get(&self, id: usize) -> &FileRecord {
        &self.files[id]
    }

    pub fn len(&self) -> usize {
        self.files.len()
    }

    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }

    pub fn total_loc(&self) -> usize {
        self.files.iter().map(|f| f.loc).sum()
    }
}

pub fn collect(root: &Path) -> Result<Inventory> {
    collect_cached(root, &mut HashMap::new())
}

/// Canonicalized root with the extended-length prefix stripped for display.
/// Exposed so the runner resolves the codearch directory (and its cache)
/// before inventory runs: the cache must be loaded to skip inventory reads.
pub fn canonical_root(root: &Path) -> Result<PathBuf> {
    let root = root
        .canonicalize()
        .with_context(|| format!("cannot open repository root {}", root.display()))?;
    Ok(strip_unc_prefix(root))
}

/// Inventory with a warm file cache. On (mtime, size) match the file is not
/// read at all: location count, class, language and content hash are reused
/// and the parse stage below hits without touching disk. `files` is updated
/// in place — refreshed shells for new/changed files, pruned of deleted ones
/// — so the caller saves the same map it ran with.
pub fn collect_cached(
    root: &Path,
    files: &mut HashMap<String, StoredFile>,
) -> Result<Inventory> {
    let root = canonical_root(root)?;

    let mut stats = ExcludeStats::default();
    let mut analyzed: Vec<FileRecord> = Vec::new();
    let mut skipped: Vec<FileRecord> = Vec::new();
    let mut read_stats = (0usize, 0usize); // (stat-hits, disk reads)

    let walker = WalkBuilder::new(&root)
        .hidden(true)
        .git_ignore(true)
        .git_global(false)
        .parents(false)
        .filter_entry(|e| {
            let name = e.file_name().to_string_lossy();
            !VENDOR_DIRS.contains(&name.as_ref())
        })
        .build();

    for entry in walker {
        let entry = match entry {
            Ok(e) => e,
            Err(_) => {
                stats.unreadable += 1;
                continue;
            }
        };

        if entry.file_type().map(|t| t.is_dir()).unwrap_or(false) {
            continue;
        }

        let abs = entry.path().to_path_buf();
        let Some(language) = Language::from_path(&abs) else {
            stats.non_supported += 1;
            continue;
        };

        let rel = match abs.strip_prefix(&root) {
            Ok(r) => r.to_string_lossy().replace('\\', "/"),
            Err(_) => continue,
        };

        let meta = match entry.metadata() {
            Ok(m) => m,
            Err(_) => {
                stats.unreadable += 1;
                continue;
            }
        };
        let bytes = meta.len();

        if bytes > MAX_SOURCE_BYTES {
            stats.too_large += 1;
            continue;
        }

        let mtime_ns = meta
            .modified()
            .ok()
            .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
            .map(|d| d.as_nanos() as u64);

        // Warm cache: same stat signature reuses everything without reading.
        if let (Some(mtime), Some(stored)) = (mtime_ns, files.get(&rel)) {
            if stored.mtime_ns == mtime && stored.size == bytes {
                let record = FileRecord {
                    id: 0, // assigned below
                    rel: rel.clone(),
                    abs,
                    language: stored.language,
                    bytes,
                    loc: stored.loc,
                    class: stored.class,
                };
                count_class(&mut stats, stored.class);
                if stored.class.is_analyzed() {
                    analyzed.push(record);
                } else {
                    skipped.push(record);
                }
                read_stats.0 += 1;
                continue;
            }
        }

        let text = match std::fs::read_to_string(&abs) {
            Ok(t) => t,
            Err(_) => {
                stats.unreadable += 1;
                continue;
            }
        };
        read_stats.1 += 1;

        let loc = text.lines().count();
        let class = classify(&rel, &text);
        count_class(&mut stats, class);

        // Refresh the cache shell. The parse stage fills `parse` below;
        // anything the run aborts before that keeps the old entry, since a
        // half-refreshed cache must never poison the next run... except it
        // would: a crash between inventory and parse leaves a shell with a
        // fresh hash but a stale parse. `parse_hash` distinguishes them —
        // only a matching pair is a hit.
        let hash = sha_hex(text.as_bytes());
        files
            .entry(rel.clone())
            .and_modify(|e| {
                e.mtime_ns = mtime_ns.unwrap_or(0);
                e.size = bytes;
                e.hash = hash.clone();
                e.loc = loc;
                e.class = class;
                e.language = language;
            })
            .or_insert_with(|| StoredFile {
                mtime_ns: mtime_ns.unwrap_or(0),
                size: bytes,
                hash,
                loc,
                class,
                language,
                parse: crate::parse::FileParse::default(),
                parse_hash: String::new(),
            });

        let record = FileRecord {
            id: 0, // assigned below
            rel,
            abs,
            language,
            bytes,
            loc,
            class,
        };

        if class.is_analyzed() {
            analyzed.push(record);
        } else {
            skipped.push(record);
        }
    }

    // Stable ordering makes the whole pipeline reproducible run to run.
    analyzed.sort_by(|a, b| a.rel.cmp(&b.rel));
    skipped.sort_by(|a, b| a.rel.cmp(&b.rel));
    for (i, f) in analyzed.iter_mut().enumerate() {
        f.id = i;
    }

    // Deleted files leave the cache so it cannot grow without bound... it is
    // still bounded by repo size either way, but stale entries are pure dead
    // weight on the next load.
    let live: std::collections::HashSet<&str> = analyzed
        .iter()
        .chain(skipped.iter())
        .map(|f| f.rel.as_str())
        .collect();
    let dropped = files.len().saturating_sub(live.len());
    files.retain(|rel, _| live.contains(rel.as_str()));
    if std::env::var_os("CODEARCH_TIME").is_some() {
        eprintln!("time inventory-cache hits={} reads={} dropped={}", read_stats.0, read_stats.1, dropped);
    }

    Ok(Inventory {
        root,
        files: analyzed,
        skipped,
        excluded: stats,
    })
}

fn count_class(stats: &mut ExcludeStats, class: FileClass) {
    match class {
        FileClass::Generated => stats.generated += 1,
        FileClass::Config => stats.config += 1,
        FileClass::Vendored => stats.declarations += 1,
        _ => {}
    }
}

fn strip_unc_prefix(p: PathBuf) -> PathBuf {
    let s = p.to_string_lossy();
    match s.strip_prefix(r"\\?\") {
        Some(rest) => PathBuf::from(rest),
        None => p,
    }
}

fn classify(rel: &str, text: &str) -> FileClass {
    if rel.ends_with(".d.ts") {
        // Declaration files describe an API surface that already exists in the
        // implementation files; mapping both doubles the noise.
        return FileClass::Vendored;
    }
    if is_generated(text) {
        return FileClass::Generated;
    }
    if is_test(rel) {
        return FileClass::Test;
    }
    if is_config(rel) {
        return FileClass::Config;
    }
    FileClass::Source
}

fn is_test(rel: &str) -> bool {
    let lower = rel.to_ascii_lowercase();
    let base = rel.rsplit('/').next().unwrap_or(rel);
    let base_lower = base.to_ascii_lowercase();
    lower.contains("__tests__/")
        || lower.contains("__mocks__/")
        || lower.starts_with("test/")
        || lower.starts_with("tests/")
        || lower.contains("/test/")
        || lower.contains("/tests/")
        || lower.contains("/e2e/")
        || lower.contains(".test.")
        || lower.contains(".spec.")
        // Python conventions: no `.test.` infix, tests live in names.
        || base_lower.starts_with("test_")
        || base_lower.ends_with("_test.py")
        || base_lower == "conftest.py"
}

fn is_config(rel: &str) -> bool {
    let base = rel.rsplit('/').next().unwrap_or(rel);
    let lower = base.to_ascii_lowercase();
    lower.contains(".config.")
        || lower.starts_with(".eslintrc")
        || lower.starts_with(".prettierrc")
        || lower == "next-env.d.ts"
        || lower == "commitlint.config.js"
}

fn is_generated(text: &str) -> bool {
    let head: String = text.chars().take(4096).collect();
    if GENERATED_MARKERS.iter().any(|m| head.contains(m)) {
        return true;
    }
    // Minification check: a single enormous line is conclusive on its own.
    text.lines().take(200).any(|l| l.len() > MINIFIED_LINE_BYTES)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn recognizes_test_paths() {
        assert!(is_test("src/auth/login.test.ts"));
        assert!(is_test("src/__tests__/login.ts"));
        assert!(is_test("tests/integration/api.ts"));
        assert!(!is_test("src/auth/login.ts"));
        // "latest" contains "test" but is not a test path.
        assert!(!is_test("src/latest/index.ts"));
    }

    #[test]
    fn recognizes_config_paths() {
        assert!(is_config("next.config.js"));
        assert!(is_config("vite.config.ts"));
        assert!(!is_config("src/config/database.ts"));
    }

    #[test]
    fn detects_generated_headers_and_minification() {
        assert!(is_generated("// @generated by protoc\nexport const A = 1;"));
        assert!(is_generated(&format!("const a=1;{}\n", "x".repeat(3000))));
        assert!(!is_generated("export function real() { return 1; }"));
    }

    #[test]
    fn declaration_files_are_not_analyzed() {
        assert_eq!(classify("src/types.d.ts", "export {}"), FileClass::Vendored);
        assert!(!FileClass::Vendored.is_analyzed());
    }

    #[test]
    fn python_test_names_are_test_classed() {
        assert!(is_test("tests/test_models.py"));
        assert!(is_test("src/test_views.py"));
        assert!(is_test("pkg/auth_test.py"));
        assert!(is_test("pkg/conftest.py"));
        assert!(!is_test("pkg/models.py"));
        assert!(!is_test("pkg/latest.py"));
    }

    #[test]
    fn django_migrations_are_generated() {
        assert!(is_generated("# Generated by Django 5.0 on 2024-01-01\n"));
        assert_eq!(
            classify("app/migrations/0001_initial.py", "# Generated by Django 5.0\n"),
            FileClass::Generated
        );
    }

    #[test]
    fn python_extension_maps_to_python() {
        assert_eq!(
            Language::from_path(std::path::Path::new("pkg/models.py")),
            Some(Language::Python)
        );
        assert_eq!(Language::Python.name(), "Python");
    }
}
