//! `codearch` — the CLI.
//!
//! The whole intended experience is one command:
//!
//! ```text
//! $ codearch .
//! ```

use anyhow::Result;
use clap::Parser;
use codearch::{LabelerKind, Options, DEFAULT_BUDGET, DEFAULT_MAX_DOMAINS};
use std::path::PathBuf;

#[derive(Parser)]
#[command(
    name = "codearch",
    about = "Analyze a repository locally and write a compact map for coding agents",
    version
)]
struct Cli {
    /// Repository root to analyze.
    #[arg(default_value = ".")]
    path: PathBuf,

    /// Where to write the map (default: <repo>/CODEBASE.md).
    #[arg(short, long)]
    out: Option<PathBuf>,

    /// Hard token budget for the generated map.
    #[arg(short, long, default_value_t = DEFAULT_BUDGET)]
    budget: usize,

    /// Maximum number of top-level domains.
    #[arg(long, default_value_t = DEFAULT_MAX_DOMAINS)]
    max_domains: usize,

    /// Clustering seed. Changing it reshuffles tie-breaks, nothing else.
    #[arg(long, default_value_t = 0x5EED)]
    seed: u64,

    /// Skip writing .codearch/index.json.
    #[arg(long)]
    no_index: bool,

    /// Ignore git history: no co-change edges, no churn term.
    #[arg(long)]
    no_git: bool,

    /// Where index.json and imports.md are written (default: <repo>/.codearch).
    #[arg(long)]
    codearch_dir: Option<PathBuf>,

    /// How domains are named. `llm` needs a binary built with --features llm.
    #[arg(long, value_enum, default_value_t = LabelerArg::Derived)]
    labeler: LabelerArg,

    /// GGUF model file. Required with --labeler llm.
    #[arg(long)]
    model: Option<PathBuf>,

    /// Threads for local inference (default: all available cores).
    #[arg(long)]
    llm_threads: Option<i32>,
}

#[derive(Copy, Clone, PartialEq, Eq, clap::ValueEnum)]
enum LabelerArg {
    /// Deterministic names from directory structure. No model, no network.
    Derived,
    /// Names generated by a local GGUF model, guarded against ungrounded output.
    Llm,
}

impl From<LabelerArg> for LabelerKind {
    fn from(a: LabelerArg) -> Self {
        match a {
            LabelerArg::Derived => LabelerKind::Derived,
            LabelerArg::Llm => LabelerKind::Llm,
        }
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    let opts = Options {
        root: cli.path,
        out: cli.out,
        budget: cli.budget,
        max_domains: cli.max_domains,
        seed: cli.seed,
        write_index: !cli.no_index,
        no_git: cli.no_git,
        codearch_dir: cli.codearch_dir,
        labeler: cli.labeler.into(),
        model_path: cli.model,
        llm_threads: cli.llm_threads,
    };

    println!("Analyzing repository...");
    let report = codearch::run(&opts)?;

    println!();
    println!("Source files:        {}", report.files);
    println!("Lines:               {}", report.loc);
    println!(
        "Est. source context: {} tokens",
        report.source_tokens_estimate
    );
    println!(
        "Import resolution:   {:.0}%{}",
        report.resolution_rate * 100.0,
        if report.unresolved > 0 {
            format!(" ({} unresolved)", report.unresolved)
        } else {
            String::new()
        }
    );
    println!(
        "Git co-change:       {}",
        if report.commits_read == 0 {
            "none (no usable history)".to_string()
        } else {
            format!(
                "{} pairs from {} commits",
                report.cochange_pairs, report.commits_read
            )
        }
    );
    println!("Domains:             {}", report.domains);
    println!(
        "Flows:               {}",
        if report.flows_dropped {
            format!("{} computed, dropped over budget", report.flows)
        } else {
            format!("{}", report.flows)
        }
    );
    println!(
        "Confidence:          {:.2}{}",
        report.confidence,
        if report.low_confidence_domains > 0 {
            format!(" ({} low-confidence domains)", report.low_confidence_domains)
        } else {
            String::new()
        }
    );
    if report.labels_fell_back > 0 {
        println!(
            "Derived fallbacks:   {} of {} domains",
            report.labels_fell_back, report.domains
        );
    }
    println!();
    println!("Generated:");
    println!("  {}", report.out_path.display());
    if let Some(p) = &report.index_path {
        println!("  {}", p.display());
    }
    println!("  {}", report.imports_path.display());
    println!();
    println!("Generated context:   {} tokens", report.map_tokens);
    println!(
        "Import index:        {} imports, {} tokens, read on demand",
        report.import_edges, report.imports_tokens
    );

    if report.used_directory_fallback {
        println!();
        println!(
            "Note: no import edges were resolved, so domains fall back to \
directory structure. Treat the grouping as layout, not architecture."
        );
    }
    if report.over_domain_cap {
        println!();
        println!(
            "Note: {} domains exceeds the cap of {}. The remaining groups share no \
imports, so merging them further would assert a relationship the code does not have.",
            report.domains, opts.max_domains
        );
    }
    if report.truncated {
        println!();
        println!("Note: the file list per domain was shortened to fit the token budget.");
    }

    Ok(())
}
