//! `codearch` — the CLI.
//!
//! The whole intended experience is one command:
//!
//! ```text
//! $ codearch .
//! ```

use anyhow::Result;
use clap::{Parser, Subcommand};
use codearch::{query, LabelerKind, Options, DEFAULT_BUDGET, DEFAULT_MAX_DOMAINS};
use std::path::PathBuf;

#[derive(Parser)]
#[command(
    name = "codearch",
    about = "Analyze a repository locally and write a compact map for coding agents",
    version,
    args_conflicts_with_subcommands = true
)]
struct Cli {
    /// Repository root to analyze.
    #[arg(default_value = ".")]
    path: PathBuf,

    /// Where to write the map (default: <repo>/CODEBASE.md).
    #[arg(short, long)]
    out: Option<PathBuf>,

    /// Hard token budget for the generated map.
    #[arg(short, long, default_value_t = DEFAULT_BUDGET)]
    budget: usize,

    /// Maximum number of top-level domains.
    #[arg(long, default_value_t = DEFAULT_MAX_DOMAINS)]
    max_domains: usize,

    /// Clustering seed. Changing it reshuffles tie-breaks, nothing else.
    #[arg(long, default_value_t = 0x5EED)]
    seed: u64,

    /// Skip writing .codearch/index.json.
    #[arg(long)]
    no_index: bool,

    /// Ignore git history: no co-change edges, no churn term.
    #[arg(long)]
    no_git: bool,

    /// Where index.json and imports.md are written (default: <repo>/.codearch).
    #[arg(long)]
    codearch_dir: Option<PathBuf>,

    /// How domains are named. `llm` needs a binary built with --features llm.
    #[arg(long, value_enum, default_value_t = LabelerArg::Derived)]
    labeler: LabelerArg,

    /// GGUF model file. Required with --labeler llm.
    #[arg(long)]
    model: Option<PathBuf>,

    /// Threads for local inference (default: all available cores).
    #[arg(long)]
    llm_threads: Option<i32>,
    /// Trained LoRA adapter applied on top of --model (M6 fine-tune path).
    #[arg(long, requires = "model")]
    lora: Option<PathBuf>,

    /// Strength of the LoRA adapter (llama.cpp --lora-scale; default 1.0).
    #[arg(long, default_value_t = 1.0)]
    lora_scale: f32,

    /// Look up the index instead of analyzing: `importers` serves the
    /// reverse import index, `callers` the route index. A directory
    /// literally named `importers` or `callers` still analyzes as
    /// `codearch ./importers`.
    #[command(subcommand)]
    command: Option<Commands>,
}

#[derive(Subcommand, Debug)]
enum Commands {
    /// Every file importing FILE, directly (depth 1) or transitively.
    Importers {
        /// File to look up, as the agent has it (`src/a.ts`, `./src/a.ts`,
        /// `src\a.ts`, or an absolute path inside the repo).
        file: String,
        /// Deepest hop to report (default: no limit).
        #[arg(long)]
        depth: Option<usize>,
        /// Emit one JSON object instead of `depth  path` lines.
        #[arg(long)]
        json: bool,
        /// Repository root (default: `.`).
        #[arg(long)]
        repo: Option<PathBuf>,
        /// Where imports.md is read from (default: <repo>/.codearch).
        #[arg(long)]
        codearch_dir: Option<PathBuf>,
    },
    /// Frontend files calling a backend view, from the route index.
    Callers {
        /// View name, e.g. `TagViewSet`.
        view: String,
        /// Emit one JSON object instead of text blocks.
        #[arg(long)]
        json: bool,
        /// Repository root (default: `.`).
        #[arg(long)]
        repo: Option<PathBuf>,
        /// Where routes.md is read from (default: <repo>/.codearch).
        #[arg(long)]
        codearch_dir: Option<PathBuf>,
    },
}

#[derive(Copy, Clone, PartialEq, Eq, clap::ValueEnum)]
enum LabelerArg {
    /// Deterministic names from directory structure. No model, no network.
    Derived,
    /// Names generated by a local GGUF model, guarded against ungrounded output.
    Llm,
}

impl From<LabelerArg> for LabelerKind {
    fn from(a: LabelerArg) -> Self {
        match a {
            LabelerArg::Derived => LabelerKind::Derived,
            LabelerArg::Llm => LabelerKind::Llm,
        }
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();

    if let Some(command) = &cli.command {
        std::process::exit(run_query(command));
    }

    let opts = Options {
        root: cli.path,
        out: cli.out,
        budget: cli.budget,
        max_domains: cli.max_domains,
        seed: cli.seed,
        write_index: !cli.no_index,
        no_git: cli.no_git,
        codearch_dir: cli.codearch_dir,
        labeler: cli.labeler.into(),
        model_path: cli.model,
        llm_threads: cli.llm_threads,
        lora_path: cli.lora,
        lora_scale: cli.lora_scale,
    };

    println!("Analyzing repository...");
    let report = codearch::run(&opts)?;

    println!();
    println!("Source files:        {}", report.files);
    println!("Lines:               {}", report.loc);
    println!(
        "Est. source context: {} tokens",
        report.source_tokens_estimate
    );
    println!(
        "Import resolution:   {:.0}%{}",
        report.resolution_rate * 100.0,
        if report.unresolved > 0 {
            format!(" ({} unresolved)", report.unresolved)
        } else {
            String::new()
        }
    );
    println!(
        "Git co-change:       {}",
        if report.commits_read == 0 {
            "none (no usable history)".to_string()
        } else {
            format!(
                "{} pairs from {} commits",
                report.cochange_pairs, report.commits_read
            )
        }
    );
    println!("Domains:             {}", report.domains);
    if report.split {
        println!("Split:               root routes to domain files");
    }
    if report.contracts > 0 {
        println!(
            "API contracts:       {} URL, {} symbol shapes",
            report.url_contracts, report.semantic_contracts
        );
    }
    println!(
        "Flows:               {}",
        if report.flows_dropped {
            format!("{} computed, dropped over budget", report.flows)
        } else {
            format!("{}", report.flows)
        }
    );
    println!(
        "Confidence:          {:.2}{}",
        report.confidence,
        if report.low_confidence_domains > 0 {
            format!(" ({} low-confidence domains)", report.low_confidence_domains)
        } else {
            String::new()
        }
    );
    if report.labels_fell_back > 0 {
        println!(
            "Derived fallbacks:   {} of {} domains",
            report.labels_fell_back, report.domains
        );
    }
    if report.labels_summary_fell_back > 0 {
        println!(
            "Summary fallbacks:   {} of {} domains (name kept, sentence derived)",
            report.labels_summary_fell_back, report.domains
        );
    }
    println!();
    println!("Generated:");
    println!("  {}", report.out_path.display());
    if let Some(p) = &report.index_path {
        println!("  {}", p.display());
    }
    println!("  {}", report.imports_path.display());
    if let Some(p) = &report.routes_path {
        println!("  {} ({} views with frontend callers)", p.display(), report.route_views);
    }
    println!();
    println!("Generated context:   {} tokens", report.map_tokens);
    println!(
        "Import index:        {} imports, {} tokens, read on demand",
        report.import_edges, report.imports_tokens
    );

    if report.used_directory_fallback {
        println!();
        println!(
            "Note: no import edges were resolved, so domains fall back to \
directory structure. Treat the grouping as layout, not architecture."
        );
    }
    if report.over_domain_cap {
        println!();
        println!(
            "Note: {} domains exceeds the cap of {}. The remaining groups share no \
imports, so merging them further would assert a relationship the code does not have.",
            report.domains, opts.max_domains
        );
    }
    if report.truncated {
        println!();
        println!("Note: the file list per domain was shortened to fit the token budget.");
    }

    Ok(())
}

/// Answer one index lookup. Returns the process exit code: 0 for answers
/// and clean misses, 2 for a missing index, an out-of-repo path, or bad
/// arguments. Queries never write anything and never re-analyze.
fn run_query(command: &Commands) -> i32 {
    match command {
        Commands::Importers {
            file,
            depth,
            json,
            repo,
            codearch_dir,
        } => {
            let repo = repo.clone().unwrap_or_else(|| PathBuf::from("."));
            let dir = codearch_dir.clone().unwrap_or_else(|| repo.join(".codearch"));
            let text = match query::index_text(&dir, "imports.md", &repo.display().to_string()) {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("{e}");
                    return 2;
                }
            };
            let target = match query::normalize_target(&repo, file) {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("{e}");
                    return 2;
                }
            };
            let hits = query::importers(&query::parse_imports(&text), &target, *depth);
            if hits.is_empty() {
                eprintln!(
                    "no importers for '{target}': nothing imports it, or it was not analyzed"
                );
                if *json {
                    println!("{}", query::importers_json(&target, &hits));
                }
                return 0;
            }
            if *json {
                println!("{}", query::importers_json(&target, &hits));
            } else {
                print!("{}", query::importers_text(&hits));
            }
            if let Some(mins) = query::index_age_minutes(&dir, "imports.md") {
                eprintln!("index written {mins} minutes ago");
            }
            0
        }
        Commands::Callers {
            view,
            json,
            repo,
            codearch_dir,
        } => {
            let repo = repo.clone().unwrap_or_else(|| PathBuf::from("."));
            let dir = codearch_dir.clone().unwrap_or_else(|| repo.join(".codearch"));
            let text = match query::index_text(&dir, "routes.md", &repo.display().to_string()) {
                Ok(t) => t,
                Err(e) => {
                    eprintln!("{e}");
                    return 2;
                }
            };
            let index = query::parse_routes(&text);
            let matches = index.get(view.as_str()).cloned().unwrap_or_default();
            if matches.is_empty() {
                let mut reason = format!("no route in the index names this view '{view}'");
                let suggestions = query::suggest_views(&index, view);
                if !suggestions.is_empty() {
                    reason.push_str(&format!("; similar indexed views: {}", suggestions.join(", ")));
                }
                eprintln!("{reason}");
                if *json {
                    println!("{}", query::callers_json(view, &matches));
                }
                return 0;
            }
            if *json {
                println!("{}", query::callers_json(view, &matches));
            } else {
                print!("{}", query::callers_text(&matches));
            }
            if let Some(mins) = query::index_age_minutes(&dir, "routes.md") {
                eprintln!("index written {mins} minutes ago");
            }
            0
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn cli(args: &[&str]) -> Cli {
        let mut full = vec!["codearch"];
        full.extend(args);
        Cli::try_parse_from(full).expect("parses")
    }

    #[test]
    fn analysis_invocations_still_parse_as_analysis() {
        assert!(cli(&["."]).command.is_none());
        assert_eq!(cli(&["src"]).path, PathBuf::from("src"));
        assert!(cli(&["--no-git", "eval/fixtures/xlang"]).command.is_none());
        assert!(cli(&["--budget", "100", "."]).command.is_none());
    }

    #[test]
    fn query_subcommands_parse_with_their_flags() {
        match cli(&["importers", "src/a.ts"]).command {
            Some(Commands::Importers { file, depth, json, .. }) => {
                assert_eq!(file, "src/a.ts");
                assert_eq!(depth, None);
                assert!(!json);
            }
            other => panic!("unexpected parse: {other:?}"),
        }
        match cli(&["callers", "TagViewSet", "--json"]).command {
            Some(Commands::Callers { view, json, .. }) => {
                assert_eq!(view, "TagViewSet");
                assert!(json);
            }
            other => panic!("unexpected parse: {other:?}"),
        }
    }

    #[test]
    fn dotted_directory_names_still_analyze() {
        // A directory literally named `importers` is a subcommand spelling;
        // `./importers` is the documented way to analyze it instead.
        assert!(cli(&["importers", "src/a.ts"]).command.is_some());
        let dotted = cli(&["./importers"]);
        assert!(dotted.command.is_none());
        assert_eq!(dotted.path, PathBuf::from("./importers"));
    }
}
