//! Stage 10 — Render.
//!
//! Job    Assemble output within a hard token budget.
//! In     everything above
//! Out    CODEBASE.md, .codearch/index.json
//! Fails  Cannot fail. Budget overflow truncates by ascending importance.
//!
//! The budget is measured with a real tokenizer rather than estimated from
//! character counts, because a map that quietly doubles its own size defeats
//! the point of the tool.
//!
//! Only the domain names and summaries come from stage 9. Everything else on
//! the page traces to a deterministic stage, and the "Not Analyzed" section is
//! mandatory: the honest boundary of the map is part of the map.

use crate::inventory::Inventory;
use crate::label::{ClusterSummary, Label};
use crate::parse::FileParse;
use crate::profile::Profile;
use crate::resolve::Resolution;
use std::sync::OnceLock;

/// Files listed per domain, tried largest-first until the budget is met.
const FILE_BUDGET_STEPS: &[usize] = &[8, 6, 5, 4, 3, 2, 1];

pub struct MapInput<'a> {
    pub inv: &'a Inventory,
    pub profile: &'a Profile,
    pub res: &'a Resolution,
    pub parsed: &'a [FileParse],
    pub summaries: &'a [ClusterSummary],
    pub labels: &'a [Label],
    pub budget: usize,
}

pub struct RenderedMap {
    pub markdown: String,
    pub tokens: usize,
    /// True when the budget forced a smaller per-domain file list.
    pub truncated: bool,
}

pub fn render_map(input: &MapInput) -> RenderedMap {
    let mut last = String::new();
    for (i, &per_domain) in FILE_BUDGET_STEPS.iter().enumerate() {
        let md = build(input, per_domain);
        let tokens = count_tokens(&md);
        if tokens <= input.budget || i == FILE_BUDGET_STEPS.len() - 1 {
            return RenderedMap {
                markdown: md,
                tokens,
                truncated: i > 0,
            };
        }
        last = md;
    }
    let tokens = count_tokens(&last);
    RenderedMap {
        markdown: last,
        tokens,
        truncated: true,
    }
}

fn build(input: &MapInput, per_domain: usize) -> String {
    let inv = input.inv;
    let mut s = String::new();

    let title = input
        .profile
        .project_name
        .clone()
        .unwrap_or_else(|| dir_name(&inv.root));
    s.push_str(&format!("# Codebase Map — {title}\n\n"));

    s.push_str(&format!(
        "Generated by Code Arch · {} analyzed files · {} lines · ~{} source tokens (est.)\n",
        inv.len(),
        inv.total_loc(),
        estimate_source_tokens(inv)
    ));
    s.push_str(&format!(
        "Import resolution: {:.0}% · {} domains\n\n",
        input.res.resolution_rate * 100.0,
        input.summaries.len()
    ));

    s.push_str("## What This Is\n\n");
    match &input.profile.description {
        Some(d) if !d.trim().is_empty() => s.push_str(&format!("{d}\n\n")),
        _ => s.push_str(&format!(
            "{title} — no description declared in package.json.\n\n"
        )),
    }

    s.push_str("## Stack\n\n");
    if input.profile.frameworks.is_empty() {
        s.push_str("No frameworks identified from the manifest.\n");
    } else {
        s.push_str(&format!("{}\n", input.profile.frameworks.join(" · ")));
    }
    let top = input.res.top_externals(8);
    if !top.is_empty() {
        let names: Vec<String> = top
            .iter()
            .map(|(name, count)| format!("{name} ({count})"))
            .collect();
        s.push_str(&format!("\nMost-referenced packages: {}\n", names.join(", ")));
    }
    s.push('\n');

    s.push_str("## Domains\n\n");
    for (i, sum) in input.summaries.iter().enumerate() {
        let label = &input.labels[i];
        s.push_str(&format!("### {}\n\n", label.name));
        s.push_str(&format!("{}\n\n", label.summary));

        if !sum.entry_points.is_empty() {
            s.push_str(&format!("Entry points: {}\n\n", sum.entry_points.join(", ")));
        }

        s.push_str("Key files:\n\n");
        for &f in sum.files.iter().take(per_domain) {
            let rel = &inv.get(f).rel;
            match file_symbols(input.parsed, f, 3) {
                Some(syms) => s.push_str(&format!("- `{rel}` — {syms}\n")),
                None => s.push_str(&format!("- `{rel}`\n")),
            }
        }
        if sum.files.len() > per_domain {
            s.push_str(&format!(
                "- …and {} more files in this domain\n",
                sum.files.len() - per_domain
            ));
        }
        s.push('\n');

        let dep_names = |ids: &[usize]| -> String {
            ids.iter()
                .filter_map(|&c| input.labels.get(c).map(|l| l.name.clone()))
                .collect::<Vec<_>>()
                .join(", ")
        };
        let deps = dep_names(&sum.depends_on);
        let rdeps = dep_names(&sum.depended_on_by);
        if !deps.is_empty() || !rdeps.is_empty() {
            let mut line = Vec::new();
            if !deps.is_empty() {
                line.push(format!("Depends on: {deps}"));
            }
            if !rdeps.is_empty() {
                line.push(format!("Depended on by: {rdeps}"));
            }
            s.push_str(&format!("{}\n\n", line.join(" · ")));
        }
    }

    s.push_str("## Task Navigation\n\n");
    for (i, sum) in input.summaries.iter().enumerate() {
        let files: Vec<String> = sum
            .files
            .iter()
            .take(3)
            .map(|&f| format!("`{}`", inv.get(f).rel))
            .collect();
        if files.is_empty() {
            continue;
        }
        s.push_str(&format!(
            "- Changes to **{}** — read {}\n",
            input.labels[i].name,
            files.join(", ")
        ));
    }
    s.push('\n');

    s.push_str("## Not Analyzed\n\n");
    let e = &inv.excluded;
    s.push_str(&format!(
        "- Excluded files: {} generated, {} type declarations, {} config, {} oversized, {} unreadable\n",
        e.generated, e.declarations, e.config, e.too_large, e.unreadable
    ));
    s.push_str(&format!(
        "- Vendor and build directories were not walked; {} non-JS/TS files were ignored\n",
        e.non_js_ts
    ));
    if !input.res.unresolved.is_empty() {
        s.push_str(&format!(
            "- {} import specifiers could not be resolved to a file and carry no edge in this map\n",
            input.res.unresolved.len()
        ));
    }
    s.push_str(
        "- This map contains no execution flows and no git co-change signal; \
relationships come from resolved imports and directory structure only\n",
    );

    s
}

fn file_symbols(parsed: &[FileParse], f: usize, n: usize) -> Option<String> {
    let p = parsed.get(f)?;
    let mut names: Vec<&str> = Vec::new();
    for sym in &p.symbols {
        if sym.exported && !names.contains(&sym.name.as_str()) {
            names.push(&sym.name);
        }
        if names.len() >= n {
            break;
        }
    }
    if names.is_empty() {
        for sym in &p.symbols {
            if !names.contains(&sym.name.as_str()) {
                names.push(&sym.name);
            }
            if names.len() >= n {
                break;
            }
        }
    }
    if names.is_empty() {
        None
    } else {
        Some(names.join(", "))
    }
}

fn estimate_source_tokens(inv: &Inventory) -> usize {
    // Roughly four bytes per token for source code; stated as an estimate on
    // the page so nobody mistakes it for a measurement.
    let bytes: u64 = inv.files.iter().map(|f| f.bytes).sum();
    (bytes / 4) as usize
}

fn dir_name(p: &std::path::Path) -> String {
    p.file_name()
        .map(|s| s.to_string_lossy().to_string())
        .unwrap_or_else(|| "repository".to_string())
}

pub fn index_json(
    inv: &Inventory,
    res: &Resolution,
    summaries: &[ClusterSummary],
    labels: &[Label],
    map_tokens: usize,
) -> String {
    let clusters: Vec<serde_json::Value> = summaries
        .iter()
        .enumerate()
        .map(|(i, s)| {
            serde_json::json!({
                "id": s.id,
                "name": labels[i].name,
                "summary": labels[i].summary,
                "files": s.files.iter().map(|&f| inv.get(f).rel.clone()).collect::<Vec<_>>(),
                "depends_on": s.depends_on,
                "depended_on_by": s.depended_on_by,
            })
        })
        .collect();

    let value = serde_json::json!({
        "version": 1,
        "root": inv.root.to_string_lossy(),
        "files": inv.len(),
        "resolution_rate": res.resolution_rate,
        "map_tokens": map_tokens,
        "clusters": clusters,
    });

    serde_json::to_string_pretty(&value).unwrap_or_else(|_| "{}".to_string())
}

static BPE: OnceLock<Option<tiktoken_rs::CoreBPE>> = OnceLock::new();

/// Measured token count, with a character-based fallback if the tokenizer
/// cannot be loaded.
pub fn count_tokens(s: &str) -> usize {
    let bpe = BPE.get_or_init(|| tiktoken_rs::cl100k_base().ok());
    match bpe {
        Some(b) => b.encode_with_special_tokens(s).len(),
        None => s.chars().count() / 4 + 1,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counts_tokens_above_zero_for_real_text() {
        let n = count_tokens("export function authenticateUser() {}");
        assert!(n > 3, "got {n}");
    }

    #[test]
    fn token_count_grows_with_length() {
        let short = count_tokens("hello world");
        let long = count_tokens(&"hello world ".repeat(50));
        assert!(long > short * 10);
    }
}
